# Generated by Django 3.1.2 on 2021-01-24 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('count', models.IntegerField()),
                ('marks_per_cq', models.IntegerField()),
                ('marks_per_wq', models.FloatField()),
                ('fm', models.IntegerField()),
                ('modified_fm', models.FloatField()),
                ('unlock_paper', models.BooleanField(default=False)),
                ('publish_result', models.BooleanField(default=False)),
                ('exam_date', models.DateField(null=True)),
                ('result_date', models.DateField(null=True)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.department')),
            ],
        ),
        migrations.CreateModel(
            name='Question_answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(max_length=100)),
                ('correct_option', models.CharField(max_length=1)),
                ('img_path', models.ImageField(null=True, upload_to='exam_images')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.paper')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('roll', models.IntegerField()),
                ('sem', models.IntegerField()),
                ('academic_year', models.IntegerField()),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.department')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=20)),
                ('dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.department')),
            ],
        ),
        migrations.CreateModel(
            name='Student_answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(max_length=1)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.question_answer')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.student')),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='paper_setter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.teacher'),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=1)),
                ('desc', models.CharField(max_length=50)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question_answer')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('om', models.FloatField()),
                ('modified_om', models.FloatField()),
                ('grade', models.CharField(max_length=10)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.paper')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.student')),
            ],
        ),
    ]
