# Generated by Django 3.1.2 on 2021-01-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_answer',
            name='op1',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question_answer',
            name='op2',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question_answer',
            name='op3',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question_answer',
            name='op4',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question_answer',
            name='correct_option',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='question_answer',
            name='img_path',
            field=models.ImageField(blank=True, null=True, upload_to='exam_images'),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
