# Generated by Django 3.1.2 on 2021-01-26 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20210126_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='role',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='role',
            new_name='user',
        ),
    ]
