# Generated by Django 3.1.2 on 2021-02-10 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20210126_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='grace_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Exam_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_left', models.DurationField()),
                ('submitted', models.BooleanField(default=False)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.paper')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.student')),
            ],
        ),
        migrations.CreateModel(
            name='Alloted_question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam_entry')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question_answer')),
            ],
        ),
    ]
