# Generated by Django 3.1.2 on 2021-02-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20210210_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='exam_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='result_date',
            field=models.DateTimeField(null=True),
        ),
    ]
