# Generated by Django 3.1.2 on 2021-02-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20210210_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='elapsed_time',
            field=models.DateTimeField(null=True),
        ),
    ]
