# Generated by Django 3.1.2 on 2021-02-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_auto_20210210_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_entry',
            name='time_left',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
