# Generated by Django 3.1.2 on 2021-02-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_auto_20210210_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_entry',
            name='question',
            field=models.ManyToManyField(to='exam.Question_answer'),
        ),
        migrations.DeleteModel(
            name='Alloted_question',
        ),
    ]
