# Generated by Django 3.1.2 on 2021-03-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_auto_20210210_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_entry',
            name='warning',
            field=models.IntegerField(default=1000),
        ),
    ]
