# Generated by Django 3.1.2 on 2021-03-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_remove_exam_entry_warning'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_entry',
            name='warning',
            field=models.IntegerField(default=1000),
        ),
    ]
