# Generated by Django 3.1.2 on 2021-04-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_exam_entry_warning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_entry',
            name='warning',
            field=models.IntegerField(default=3),
        ),
    ]
