# Generated by Django 3.1.2 on 2021-06-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_auto_20210420_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_entry',
            name='warning',
            field=models.IntegerField(default=12),
        ),
    ]
