# Generated by Django 3.1.2 on 2021-06-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_auto_20210613_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_entry',
            name='warning',
            field=models.IntegerField(default=20),
        ),
    ]
