# Generated by Django 4.0.2 on 2022-07-14 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_auto_20210614_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='name',
        ),
    ]
